server:
  port: 18085
spring:
  application:
    name: nacos-gateway-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: nacos-route
        uri: lb://nacos-gateway-provider
        predicates:
        - Path=/nacos/**
        filters:
        - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: '*'
