server:
  port: 18089
spring:
  application:
    name: sentinel-example
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
nacos:
  serverAddr: 127.0.0.1:8848
  flowdataId: sentinel-nacos-flow.yaml
  group: DEFAULT_GROUP
  degradedataId: sentinel-nacos-degrade.yaml